name: bypassCF cron

on:
  schedule:
    # 每天 UTC 时间 18:00 运行
    - cron: "0 18 * * *"
  workflow_dispatch: # 允许手动触发

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 20 # 设置作业超时时间为20分钟

    strategy:
      matrix:
        node-version: [20.x]

    steps:
      - uses: actions/checkout@v3 # 检出仓库

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: |
          npm install
          sudo apt install -y xvfb

      - name: Load environment variables
        run: |
          echo "Debug: Checking if .env file exists..."

          # 检查 .env 文件是否存在
          if [ -f .env ]; then
            echo ".env file found. Loading environment variables from .env file"
            
            # 加载 .env 文件中的默认值
            set -a
            source .env
            set +a
            
            echo "Loaded .env variables:"
            cat .env
          else
            echo ".env file not found. Skipping loading."
          fi

          # Debug: 确认环境变量已加载
          echo "Debug: USERNAMES = $USERNAMES"
          echo "Debug: PASSWORDS = $PASSWORDS"
          echo "Debug: WEBSITE = $WEBSITE"

          # 如果 GitHub Secrets 中设置了环境变量，则覆盖默认值
          if [ -n "${{ secrets.USERNAMES }}" ]; then
            echo "Using GitHub Secret for USERNAMES"
            echo "USERNAMES=${{ secrets.USERNAMES }}" >> $GITHUB_ENV
          else
            echo "USERNAMES=${USERNAMES}" >> $GITHUB_ENV
          fi

          if [ -n "${{ secrets.PASSWORDS }}" ]; then
            echo "Using GitHub Secret for PASSWORDS"
            echo "PASSWORDS=${{ secrets.PASSWORDS }}" >> $GITHUB_ENV
          else
            echo "PASSWORDS=${PASSWORDS}" >> $GITHUB_ENV
          fi

          if [ -n "${{ secrets.WEBSITE }}" ]; then
            echo "Using GitHub Secret for WEBSITE"
            echo "WEBSITE=${{ secrets.WEBSITE }}" >> $GITHUB_ENV
          else
            echo "WEBSITE=${WEBSITE}" >> $GITHUB_ENV
          fi

          # Debug: 输出最终的环境变量值
          echo "Final values in GITHUB_ENV:"
          cat $GITHUB_ENV
        shell: bash
      - name: Run a script
        run: xvfb-run node bypasscf.js
