name: bypassCF cron (使用这个)
# GitHub.secrets优先级最高，即使没有设置对应的变量，它也会读取，这时变量为空值，导致报错，.env读取的变量无法覆盖这个值
on:
  schedule:
    # 每天 UTC 时间 18:00 运行
    - cron: "0 18 * * *"
  workflow_dispatch: # 允许手动触发

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 20 # 设置作业超时时间为20分钟

    strategy:
      matrix:
        node-version: [20.x]

    steps:
      - uses: actions/checkout@v3 # 检出仓库

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: |
          npm install
          sudo apt install -y xvfb

      - name: Load environment variables
        run: |
          echo "Debug: Checking if .env file exists..."

          # 检查 .env 文件是否存在
          if [ -f .env ]; then
            echo ".env file found. Loading environment variables from .env file"
            
            # 加载 .env 文件中的默认值
            set -a
            source .env
            set +a
            
            echo "Loaded .env variables:"
          else
            echo ".env file not found. Skipping loading."
          fi

          # 如果 GitHub Secrets 中设置了环境变量，则覆盖默认值
          if [ -n "${{ secrets.USERNAMES }}" ] && [ ! -z "${{ secrets.USERNAMES }}" ]; then
            echo "Using GitHub Secret for USERNAMES"
            echo "USERNAMES=${{ secrets.USERNAMES }}" >> $GITHUB_ENV
          else
            echo "USERNAMES=${USERNAMES}" >> $GITHUB_ENV
          fi

          if [ -n "${{ secrets.PASSWORDS }}" ] && [ ! -z "${{ secrets.PASSWORDS }}" ]; then
            echo "Using GitHub Secret for PASSWORDS"
            PASSWORD_ESCAPED="${{ secrets.PASSWORDS }}" && PASSWORD_ESCAPED=${PASSWORD_ESCAPED//\#/\\#}
            echo "PASSWORDS=$PASSWORD_ESCAPED" >> $GITHUB_ENV
          else
            PASSWORD_ESCAPED="${PASSWORDS}" && PASSWORD_ESCAPED=${PASSWORD_ESCAPED//\#/\\#}
            echo "PASSWORDS=$PASSWORD_ESCAPED" >> $GITHUB_ENV
          fi

          if [ -n "${{ secrets.WEBSITE }}" ] && [ ! -z "${{ secrets.WEBSITE }}" ]; then
            echo "Using GitHub Secret for WEBSITE"
            echo "WEBSITE=${{ secrets.WEBSITE }}" >> $GITHUB_ENV
          else
            echo "WEBSITE=${WEBSITE}" >> $GITHUB_ENV
          fi

        shell: bash

      - name: Run a script
        run: xvfb-run node bypasscf.js
