name: bypassCF cron

on:
  schedule:
    # 每天 UTC 时间 18:00 运行
    - cron: "0 18 * * *"
  workflow_dispatch: # 允许手动触发

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 20 # 设置作业超时时间为20分钟

    strategy:
      matrix:
        node-version: [20.x]

    steps:
      - uses: actions/checkout@v3 # 检出仓库

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: |
          npm install
          sudo apt install -y xvfb

      - name: Load environment variables
        id: load-env
        run: |
          # 加载 .env 文件中的默认值
          if [ -f .env ]; then
            echo "Loading environment variables from .env file"
            export $(grep -v '^#' .env | xargs)
          fi

          # 如果 GitHub Secrets 中设置了环境变量，则覆盖默认值
          if [ -n "${{ secrets.USERNAMES }}" ]; then
            echo "USERNAMES=${{ secrets.USERNAMES }}" >> $GITHUB_ENV
          else
            echo "USERNAMES=${USERNAMES}" >> $GITHUB_ENV
          fi

          if [ -n "${{ secrets.PASSWORDS }}" ]; then
            echo "PASSWORDS=${{ secrets.PASSWORDS }}" >> $GITHUB_ENV
          else
            echo "PASSWORDS=${PASSWORDS}" >> $GITHUB_ENV
          fi

          # Debug: 输出 WEBSITE 的值
          echo "Debug: Checking if GitHub Secret 'WEBSITE' is set..."

          if [ -n "${{ secrets.WEBSITE }}" ]; then
            echo "Debug: GitHub Secret 'WEBSITE' is set, using it."
            echo "WEBSITE=${{ secrets.WEBSITE }}" >> $GITHUB_ENV
          else
            echo "Debug: GitHub Secret 'WEBSITE' is not set, using value from environment or .env file."
            echo "WEBSITE=${WEBSITE}" >> $GITHUB_ENV
          fi

          # Debug: 输出最后设置的 WEBSITE 值
          echo "Debug: Final WEBSITE value is set to $(cat $GITHUB_ENV | grep WEBSITE)"

      - name: Run a script
        run: xvfb-run node bypasscf.js
